In [5]:
import pandas as pd

data = "../data/"

In [7]:
#Dataset 1
mono = pd.read_csv(data + "monotowns_2026.csv", encoding="utf-8-sig")
print(mono.shape)
mono.head()

(264, 3)

,number,municipality,region
0,1,Городской округ город Райчихинск Амурской области,Амурская область
1,2,Онежский муниципальный округ Архангельской обл...,Архангельская область
2,3,Городской округ город Фокино Брянской области,Брянская область
3,4,Муниципальное образование городской округ Енак...,Донецкая Народная Республика
4,5,Городской округ Мариуполь Донецкой Народной Ре...,Донецкая Народная Республика

In [9]:
#Assigning the category to the monotowns (they are split into three categories)
mono["category"] = pd.cut(mono["number"], bins=[0, 52, 201, 264], labels=[1, 2, 3])
mono["category"].value_counts()

category
2    149
3     63
1     52
Name: count, dtype: int64

In [11]:
mono[mono["municipality"].str.contains("Сланцев")]

,number,municipality,region,category
108,109,Сланцевское городское поселение Сланцевского м...,Ленинградская область,2

In [13]:
#Dataset 2
population = pd.read_csv(data + "raw\data_Y48112027_year2025_112_v20260928.csv", sep = ";")
print(population.shape)
print(population.columns.tolist())
population.head()

(31934, 22)
['indicator_section_code', 'indicator_section', 'indicator_code', 'indicator_name', 'mest', 'region_id', 'region_name', 'mun_level', 'mun_district', 'municipality', 'oktmo', 'mun_type', 'mun_type_oktmo', 'oktmo_stable', 'oktmo_history', 'oktmo_year_from', 'oktmo_year_to', 'year', 'indicator_value', 'indicator_unit', 'indicator_period', 'comment']

,indicator_section_code,indicator_section,indicator_code,indicator_name,mest,region_id,region_name,mun_level,mun_district,municipality,...,mun_type_oktmo,oktmo_stable,oktmo_history,oktmo_year_from,oktmo_year_to,year,indicator_value,indicator_unit,indicator_period,comment
0,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Все население,1,Алтайский край,Муниципальное образование верхнего уровня,Залесовский муниципальный округ,Залесовский муниципальный округ,...,Муниципальный округ,01512000,Изменен тип и название,2022,2025,2025,11043.0,Человек,На 1 января,CD
1,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Городское население,1,Алтайский край,Муниципальное образование верхнего уровня,Залесовский муниципальный округ,Залесовский муниципальный округ,...,Муниципальный округ,01512000,Изменен тип и название,2022,2025,2025,NaN,Человек,На 1 января,CD
2,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Сельское население,1,Алтайский край,Муниципальное образование верхнего уровня,Залесовский муниципальный округ,Залесовский муниципальный округ,...,Муниципальный округ,01512000,Изменен тип и название,2022,2025,2025,11043.0,Человек,На 1 января,CD
3,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Городское население,1,Алтайский край,Муниципальное образование верхнего уровня,Муниципальный округ Змеиногорский район,Муниципальный округ Змеиногорский район,...,Муниципальный округ,01514000,Изменен тип и название,2025,2025,2025,9110.0,Человек,На 1 января,CD
4,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Все население,1,Алтайский край,Муниципальное образование верхнего уровня,Муниципальный округ Змеиногорский район,Муниципальный округ Змеиногорский район,...,Муниципальный округ,01514000,Изменен тип и название,2025,2025,2025,15587.0,Человек,На 1 января,CD

In [15]:
population[population.apply(lambda row: row.astype(str).str.contains("Сланцев").any(), axis=1)].head(20)

,indicator_section_code,indicator_section,indicator_code,indicator_name,mest,region_id,region_name,mun_level,mun_district,municipality,...,mun_type_oktmo,oktmo_stable,oktmo_history,oktmo_year_from,oktmo_year_to,year,indicator_value,indicator_unit,indicator_period,comment
13714,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Сельское население,41,Ленинградская область,Муниципальное образование верхнего уровня,Сланцевский муниципальный район,Сланцевский муниципальный район,...,Муниципальный район,41642000,Без изменений,2010,2025,2025,10736.0,Человек,На 1 января,CD
13715,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Городское население,41,Ленинградская область,Муниципальное образование верхнего уровня,Сланцевский муниципальный район,Сланцевский муниципальный район,...,Муниципальный район,41642000,Без изменений,2010,2025,2025,32984.0,Человек,На 1 января,CD
13716,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Все население,41,Ленинградская область,Муниципальное образование верхнего уровня,Сланцевский муниципальный район,Сланцевский муниципальный район,...,Муниципальный район,41642000,Без изменений,2010,2025,2025,43720.0,Человек,На 1 января,CD
13717,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Все население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Сланцевское,...,Городское поселение,CD,CD,CD,CD,2025,34127.0,Человек,На 1 января,CD
13718,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Сельское население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Сланцевское,...,Городское поселение,CD,CD,CD,CD,2025,1143.0,Человек,На 1 января,CD
13719,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Городское население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Сланцевское,...,Городское поселение,CD,CD,CD,CD,2025,32984.0,Человек,На 1 января,CD
13720,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Все население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Выскатское,...,Сельское поселение,CD,CD,CD,CD,2025,2222.0,Человек,На 1 января,CD
13721,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Сельское население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Выскатское,...,Сельское поселение,CD,CD,CD,CD,2025,2222.0,Человек,На 1 января,CD
13722,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Все население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Загривское,...,Сельское поселение,CD,CD,CD,CD,2025,980.0,Человек,На 1 января,CD
13723,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Сельское население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Загривское,...,Сельское поселение,CD,CD,CD,CD,2025,980.0,Человек,На 1 января,CD
13724,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Все население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Новосельское,...,Сельское поселение,CD,CD,CD,CD,2025,1753.0,Человек,На 1 января,CD
13725,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Сельское население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Новосельское,...,Сельское поселение,CD,CD,CD,CD,2025,1753.0,Человек,На 1 января,CD
13726,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Сельское население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Гостицкое,...,Сельское поселение,CD,CD,CD,CD,2025,1516.0,Человек,На 1 января,CD
13727,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Все население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Гостицкое,...,Сельское поселение,CD,CD,CD,CD,2025,1516.0,Человек,На 1 января,CD
13728,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Все население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Старопольское,...,Сельское поселение,CD,CD,CD,CD,2025,2415.0,Человек,На 1 января,CD
13729,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Сельское население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Старопольское,...,Сельское поселение,CD,CD,CD,CD,2025,2415.0,Человек,На 1 января,CD
13730,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Сельское население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Черновское,...,Сельское поселение,CD,CD,CD,CD,2025,707.0,Человек,На 1 января,CD
13731,31,Население,Y48112027,Оценка численности населения на 1 января текущ...,Все население,41,Ленинградская область,Муниципальное образование нижнего уровня,Сланцевский муниципальный район,Черновское,...,Сельское поселение,CD,CD,CD,CD,2025,707.0,Человек,На 1 января,CD

In [17]:
#Slantsy's population 
cols = ["region_name", "municipality", "mun_type", "oktmo", "oktmo_stable", "year", "indicator_value"]
slantsy = population[population["municipality"].str.contains("Сланцев", na=False)][cols].sort_values("year")
slantsy

,region_name,municipality,mun_type,oktmo,oktmo_stable,year,indicator_value
13714,Ленинградская область,Сланцевский муниципальный район,Муниципальный район,41642000,41642000,2025,10736.0
13715,Ленинградская область,Сланцевский муниципальный район,Муниципальный район,41642000,41642000,2025,32984.0
13716,Ленинградская область,Сланцевский муниципальный район,Муниципальный район,41642000,41642000,2025,43720.0
13717,Ленинградская область,Сланцевское,Городское поселение,41642101,CD,2025,34127.0
13718,Ленинградская область,Сланцевское,Городское поселение,41642101,CD,2025,1143.0
13719,Ленинградская область,Сланцевское,Городское поселение,41642101,CD,2025,32984.0

In [20]:
population["mun_type"].value_counts()

mun_type
Сельское поселение                                             22977
Муниципальный район                                             2996
Городское поселение                                             2652
Муниципальный округ                                             1405
Городской округ, городской округ с внутригородским делением     1239
Внутригородская территория города федерального значения          520
Внутригородской район                                            124
Межселенная территория                                            18
Субъект РФ                                                         3
Name: count, dtype: int64

In [24]:
print(population["year"].min(), "to", population["year"].max())

2025 to 2025

In [26]:
new_regions = ["Донецкая", "Луганская", "Запорожская", "Херсонская"]
population[population["region_name"].str.contains("|".join(new_regions), na=False)]["region_name"].unique()

<StringArray>
[]
Length: 0, dtype: str