In [1]:
import pandas as pd

data = "../data/"

In [3]:
mono = pd.read_csv(data + "monotowns_2026.csv", encoding="utf-8-sig")
print(mono.shape)
mono.head()

(264, 3)

,number,municipality,region
0,1,Городской округ город Райчихинск Амурской области,Амурская область
1,2,Онежский муниципальный округ Архангельской обл...,Архангельская область
2,3,Городской округ город Фокино Брянской области,Брянская область
3,4,Муниципальное образование городской округ Енак...,Донецкая Народная Республика
4,5,Городской округ Мариуполь Донецкой Народной Ре...,Донецкая Народная Республика

In [11]:
#Assigning the category to the monotowns (they are split into three categories)
mono["category"] = pd.cut(mono["number"], bins=[0, 52, 201, 264], labels=[1, 2, 3])
mono["category"].value_counts()

category
2    149
3     63
1     52
Name: count, dtype: int64

In [9]:
mono[mono["municipality"].str.contains("Сланцев")]

,number,municipality,region,category
108,109,Сланцевское городское поселение Сланцевского м...,Ленинградская область,2